### ISSUE TITLE
pls publish the java client jar to central maven repository

### ISSUE THREAD

**Issue by lilyhe123** [voyager-client/java#5]

**Comment by tamalsaha** [comment]
Filed for approval for Sonatype https://issues.sonatype.org/browse/OSSRH-40701

**Comment by tamalsaha** [comment]
Release process:
https://gist.github.com/tamalsaha/ca5c2d5a1ac3351f47a1daf65f00d00f

- https://github.com/kubernetes-client/java/blob/master/RELEASES.md
- https://central.sonatype.org/pages/apache-maven.html
- https://oss.sonatype.org/#stagingRepositories

**Comment by tamalsaha** [comment]
I have released 0.1.0 . https://oss.sonatype.org/content/groups/public/com/appscode/voyager/client-java/ . It should be usable now. It takes around 7-8 hours to show up in https://search.maven.org/#search%7Cga%7C1%7Cappscode
